# Generated by Django 5.0 on 2023-12-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name',), 'verbose_name_plural': 'Items'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='descreption',
            new_name='description',
        ),
    ]
